### ISSUE TITLE
Incompatibility with MC v1.20.4

### ISSUE THREAD

**Issue by K9Paradox** [sleepingdragoninn/inventory-tabs#35] opened 2024-02-16 00:11 UTC
Server thread crash when joining a world. Not sure if the 1.20 update was specifically for 1.20 or 1.20+ ex 1.20.4
[Crash Log](https://mclo.gs/699ZOLT)

**Comment by sleepingdragoninn** [comment] 2024-02-16 00:28
duplicate of #17

**Closed as not planned by sleepingdragoninn** 2024-02-16 00:28 UTC
