### ISSUE TITLE
Inactive tab background is missing in modpack

### ISSUE THREAD

**Issue by Trimint123** [sleepingdragoninn/inventory-tabs#30] opened 2024-01-31 15:58 UTC
Self explanatory. And I had no idea what mod that may had caused it.
![image](https://github.com/sisby-folk/inventory-tabs/assets/25479107/60d69c63-250d-4944-afdf-a0f73d803331)

**Comment by sleepingdragoninn** [comment] 2024-01-31 22:55
Inventory tabs uses the vanilla tab textures on the latest version - so the creative screen should be equally broken if it hasn't been mixed into.

**Comment by Trimint123** [comment] 2024-02-01 00:06
> Inventory tabs uses the vanilla tab textures on the latest version - so the creative screen should be equally broken if it hasn't been mixed into.

I checked the tabs in Creative. No issue there.

**Comment by sleepingdragoninn** [comment] 2024-02-01 00:31
can you provide your `logs/latest.log` file by uploading it to https://mclo.gs/ and posting the link?

**Comment by Trimint123** [comment] 2024-02-01 02:14
Here ya go.
https://mclo.gs/pna3yT2

**Comment by sleepingdragoninn** [comment] 2024-02-01 02:19
your log is full of gl errors. a mod is probably breaking rendering.

![image](https://github.com/sisby-folk/inventory-tabs/assets/55819817/56191c93-42dc-409b-89ab-bdddd05fd694)

if you're committed to finding the cause of the bug, you can spend time bisecting it by disabling half of the mods in your modpack, then launching the game - if its still broken, halve it again, if it's not, enable half the disabled mods, etc until you know which mod breaks it.

**Comment by Trimint123** [comment] 2024-02-01 02:20
Alright, I'll look forward to it.

**Comment by Trimint123** [comment] 2024-02-01 03:49
Found the issue. InvMove was the cause of it.
https://github.com/PieKing1215/InvMove

**Comment by sleepingdragoninn** [comment] 2024-02-01 06:13
they turn off background rendering https://github.com/PieKing1215/InvMove/blob/master/crossversion/common/src/main/java/me/pieking1215/invmove/mixin/client/BackgroundMixin.java

we could probably fudge it a bit and render the disabled tabs in the foreground.

**Closed as completed** 2024-02-04 00:11 UTC
Labels: incompatibility

**Comment by sleepingdragoninn** [comment] 2024-02-04 00:37
fixed up as 1.1.8 now
