### ISSUE TITLE
Unable to access last page

### ISSUE THREAD

**Issue by kwmbe** [sleepingdragoninn/inventory-tabs#66] opened 2024-12-16 21:12 UTC
Version 1.4.0+1.20

When near a lot of interactable blocks, any blocks past the 2 page limit will no longer be accessable when going to a previous page.
![image](https://github.com/user-attachments/assets/6a0b823a-e4dd-4336-a59c-94599f25d6fd)
![image](https://github.com/user-attachments/assets/3d8ca769-1460-42cf-8414-62393dc614d6)

**Comment by kwmbe** [comment] 2024-12-16 22:26
After placing down even more interactable blocks, I can now access the third page. Now I'm not sure what's causing the bug.

![image](https://github.com/user-attachments/assets/02c1bd24-3ef1-4848-8d9d-51cbbcaefee5)

**Comment by sleepingdragoninn** [comment] 2024-12-31 02:54
dupe of #57

**Closed as not planned by sleepingdragoninn** 2024-12-31 02:54 UTC
